# Generated by Django 3.2.3 on 2021-05-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0002_listen_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('subnet_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='subnet IP')),
                ('subnet_cidr', models.PositiveSmallIntegerField(default=0, verbose_name='subnet CIDR')),
                ('stating_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='starting IP range')),
                ('ending_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ending IP range')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'ordering': ['order', 'name'],
            },
        ),
    ]
