# Generated by Django 3.2.3 on 2021-05-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0003_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('stating_ip', models.GenericIPAddressField(verbose_name='starting IP range')),
                ('ending_ip', models.GenericIPAddressField(verbose_name='ending IP range')),
                ('lease_time', models.PositiveIntegerField(default=12, verbose_name='lease time')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'DHCP range',
                'verbose_name_plural': 'DHCP ranges',
                'ordering': ['order', 'name'],
            },
        ),
    ]
