# Generated by Django 3.2.3 on 2021-05-30 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0005_dhcp_option_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpDefaultOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('character_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='character value')),
                ('numeric_value', models.IntegerField(blank=True, null=True, verbose_name='numeric value')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnsmasq.dhcpoptiontype', verbose_name='option')),
            ],
            options={
                'verbose_name': 'DHCP default option',
                'verbose_name_plural': 'DHCP default options',
                'ordering': ['option__option'],
            },
        ),
    ]
