# Generated by Django 3.2.3 on 2021-05-30 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0006_dhcp_default_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpDefaultOptionIpV4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(protocol='ipv4', verbose_name='address')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnsmasq.dhcpdefaultoption', verbose_name='option')),
            ],
            options={
                'verbose_name': 'DHCP default option IPv4 address',
                'verbose_name_plural': 'DHCP default options IPv4 addresses',
                'ordering': ['option', 'order'],
            },
        ),
    ]
