# Generated by Django 3.2.3 on 2021-05-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0007_dhcp_default_option_ipv4'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpDefaultOptionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'DHCP default option (extended)',
                'verbose_name_plural': 'DHCP default options (extended)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dnsmasq.dhcpdefaultoption',),
        ),
    ]
