# Generated by Django 3.2.3 on 2021-06-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0010_dhcp_range_rename_stating_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcpdefaultoption',
            name='option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dnsmasq.dhcpoptiontype', verbose_name='option'),
        ),
    ]
