# Generated by Django 3.2.3 on 2021-06-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0011_dhcp_default_option_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('action', models.CharField(max_length=255, unique=True, verbose_name='action')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['order', 'name'],
            },
        ),
    ]
