# Generated by Django 3.2.3 on 2021-06-13 13:27

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0013_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('mac_address', macaddress.fields.MACAddressField(integer=True, unique=True, verbose_name='mac address')),
                ('ignored', models.BooleanField(default=False, verbose_name='ignored')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
                'ordering': ['name'],
            },
        ),
    ]
