# Generated by Django 3.2.3 on 2021-06-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0014_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host',
            new_name='DhcpHost',
        ),
        migrations.AlterModelOptions(
            name='dhcphost',
            options={'ordering': ['name'], 'verbose_name': 'DHCP host', 'verbose_name_plural': 'DHCP hosts'},
        ),
    ]
