# Generated by Django 3.2.3 on 2021-06-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0015_host_rename_dhcp_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpdefaultoption',
            name='forced',
            field=models.BooleanField(default=False, verbose_name='forced'),
        ),
    ]
