# Generated by Django 3.2.3 on 2021-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0016_dhcp_default_option_forced'),
    ]

    operations = [
        migrations.CreateModel(
            name='DhcpTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'DHCP tag',
                'verbose_name_plural': 'DHCP tags',
                'ordering': ['name'],
            },
        ),
    ]
