# Generated by Django 3.2.3 on 2021-06-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0017_dhcp_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DhcpDefaultOptionIpV4',
            new_name='DhcpOptionIpV4',
        ),
        migrations.AlterModelOptions(
            name='dhcpoptionipv4',
            options={'ordering': ['option', 'order'], 'verbose_name': 'DHCP option IPv4 address', 'verbose_name_plural': 'DHCP options IPv4 addresses'},
        ),
    ]
