# Generated by Django 3.2.3 on 2021-06-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0018_dhcp_option_ipv4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DhcpDefaultOptionProxy',
        ),
        migrations.RenameModel(
            old_name='DhcpDefaultOption',
            new_name='DhcpOption',
        ),
        migrations.AlterModelOptions(
            name='dhcpoption',
            options={'ordering': ['option__option'], 'verbose_name': 'DHCP option', 'verbose_name_plural': 'DHCP options'},
        ),
        migrations.CreateModel(
            name='DhcpOptionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'DHCP option (extended)',
                'verbose_name_plural': 'DHCP options (extended)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dnsmasq.dhcpoption',),
        ),
    ]
