# Generated by Django 3.2.3 on 2021-06-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0019_dhcp_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpoption',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnsmasq.dhcptag', verbose_name='tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dhcpoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dnsmasq.dhcpoptiontype', verbose_name='option'),
        ),
        migrations.AlterUniqueTogether(
            name='dhcpoption',
            unique_together={('tag', 'option')},
        ),
    ]
