# Generated by Django 3.2.3 on 2021-06-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0023_dhcp_host_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcphost',
            name='hostname',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='hostname'),
        ),
    ]
