# Generated by Django 3.2.3 on 2021-06-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0025_dhcp_range_lease_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcphost',
            name='lease_time',
            field=models.IntegerField(default=0, verbose_name='lease time'),
        ),
    ]
