# Generated by Django 3.2.3 on 2021-08-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0027_alter_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcptag',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
