# Generated by Django 3.2.3 on 2021-08-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0028_dhcptag_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='dhcphost',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='dhcpoption',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='dhcpoptionipv4',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='dhcpoptiontype',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='dhcprange',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='dhcptag',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='listenaddress',
            old_name='status',
            new_name='is_active'
        ),
        migrations.RenameField(
            model_name='option',
            old_name='status',
            new_name='is_active'
        ),
    ]
