# Generated by Django 3.2.3 on 2021-08-24 23:01

from django.db import migrations, models

from dnsmasq.constants import SETTING_CONFIGURATION_PATH


def insert_default_settings(apps, schema_editor):
    """
    Insert some default settings
    """
    # Don't import the Configuration model directly as it may be a newer
    # version than this migration expects.
    Setting = apps.get_model('dnsmasq', 'Setting')
    Setting.objects.create(name=SETTING_CONFIGURATION_PATH,
                           description='Path for configuration export',
                           value='',
                           is_active=True)

def delete_default_settings(apps, schema_editor):
    """
    Delete some default settings
    """
    # Don't import the Configuration model directly as it may be a newer
    # version than this migration expects.
    Setting = apps.get_model('dnsmasq', 'Setting')
    queryset = Setting.objects.filter(name=SETTING_CONFIGURATION_PATH)
    queryset.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0030_rename_status_to_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='value')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(code=insert_default_settings,
                             reverse_code=delete_default_settings)
    ]
