# Generated by Django 3.2.3 on 2021-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0031_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=255, verbose_name='option'),
        ),
    ]
