# Generated by Django 3.2.3 on 2021-09-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0034_order_by_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcphost',
            options={'ordering': ['order', '-is_active', 'name'], 'verbose_name': 'DHCP host', 'verbose_name_plural': 'DHCP hosts'},
        ),
        migrations.AddField(
            model_name='dhcphost',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
    ]
