# Generated by Django 3.2.3 on 2021-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0036_dhcptag_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dhcpoption',
            options={'ordering': ['tag', 'order', '-is_active', 'option__option'], 'verbose_name': 'DHCP option', 'verbose_name_plural': 'DHCP options'},
        ),
        migrations.AddField(
            model_name='dhcpoption',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
    ]
