# Generated by Django 3.2.7 on 2021-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnsmasq', '0039_setting_leases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhcphost',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hostname'),
        ),
    ]
